### ISSUE TITLE
Help needed for a project

### ISSUE THREAD

**Issue by oesah** [obicho/docker-nginx-wordpress-django#1]
Hey, I could not find a way to contact you, so I try here. 

I need help setting up this stack. I have docker, nginx, django and postgres. 

I need to add wordpress to the stack. It should be available for local development and of course in production behind nginx. 

Can you help me out? You can contact me via o.sahin@oesah.de

**Comment by obicho** [comment]
Did you try what I have here?

**Comment by obicho** [comment]
Did you try this docker compose setup?
